[package]
name = "redis-starter-rust"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2018"

# DON'T EDIT THIS!
#
# This is only for local usage, any changes here will not reflect when
# CodeCrafters tests your code.
#
# DON'T EDIT THIS!
[dependencies]
